name: Publish Extension Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Check out the extension under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install packages.
      - name: Install packages
        run: npm install
      # Publish the extension.
      - uses: lannonbr/vsce-action@2.0.0
        with:
          args: "publish $github.event.release.tag_name -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}